import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class Selected {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id;

  final double calories;
  final int steps;
  final double distance;
  final DateTime dateTime;

  Selected(this.id, this.calories, this.steps, this.distance, this.dateTime);

} //Selected